[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
serverAddress = "sao.karpaylegal.com"
gatherUsageStats = false