[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[global]
developmentMode = false
logLevel = "warning"
suppressDeprecationWarnings = true

[logger]
level = "warning"